accounts/urls.py
from django.urls import path
from .views import SignupView, profile
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignupView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path("profile/", profile, name="profile")
]

course/urls.py
from django.urls import path
from . import views


app_name = 'course'
urlpatterns = [
    path('access/<int:pk>', views.AccessCourse.as_view(), name='access'),
    path('enroll/<int:pk>', views.enroll, name='enroll'),
    path('courses/<int:pk>', views.CourseDetailView.as_view(), name="courseDetail"),
    path('courses', views.CourseListView.as_view(), name="courseList"),
    path('', views.HomeView.as_view(), name="home"),
]

educative/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('accounts/', include('accounts.urls', namespace='account')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
# from django.utils import timezone


class UserManager(BaseUserManager):
    use_in_migrations = True
    
    def _create_user(self, email, password, first_name, last_name, **other):
        """
        Create and save user with given first name, last name and email
        """
        if not (email or password or first_name or last_name):
            raise ValueError('Email, Password, First Name and Last Name are required field!!')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **other)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email=None, first_name=None, last_name=None, password=None, **other):
        other.setdefault('is_superuser', False)
        other.setdefault('is_staff', False)


    def create_superuser(self, email=None, password=None, first_name=None, last_name=None, **other):
        """
        Create a superuser
        give some default permissions
        """

        other.setdefault('is_superuser', True)
        other.setdefault('is_staff', True)
        
        if other.get('is_superuser') is not True:
            raise ValueError('Superuser must be is_superuser')
        elif other.get('is_staff') is not True:
            raise ValueError('Superuser must be is_staff')

        
        return self._create_user(email, password, first_name, last_name, **other)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Django custom user model
    AbstructBaseUser: Defines the properties required for user mode;
    PermissionMixin: Have some methods to check or set permissions
    """

    email = models.EmailField(_('email'), max_length=128, unique=True, error_messages= {
        'unique': _("A user with that username already exists."),
    })
    first_name = models.CharField(_('first name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=80)

    date_joined = models.DateTimeField(auto_now_add=True)

    # teacher can post courses
    is_teacher = models.BooleanField(_('user is teacher'), default=False)

    # staff user can access adminpanel
    is_staff = models.BooleanField(_('is staff'), help_text='Can access admin panel', default=False)
    is_active = models.BooleanField(_('user is active'), default=True, help_text='Don\'t delete user, set False')

    # password and last_login is defined in AbstructBaseUser

    REQUIRED_FIELDS = ['first_name', 'last_name']

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return self.email
    
    @property
    def get_full_name(self):
        return self.first_name + ' ' + self.last_name
    

course/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    # @property
    # def get_absolute_url(self):
    #     return reverse('posts:listCategories')


class Course(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    category = models.ForeignKey(Category, default=1, on_delete=models.PROTECT)
    thumbnail = models.URLField(help_text='image url from unsplash/pexels')
    published_on = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    author = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Enrollment(models.Model):
    student = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Enrollments'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django import forms


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=128)
    last_name = forms.CharField(max_length=128)
    email = forms.EmailField(max_length=128)
    is_teacher = forms.BooleanField(label='Are you a teacher??', required=False)

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    # override
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

        if user.is_teacher:
            group = Group.objects.get(name='Teacher')
            user.groups.add(group)
        else:
            group = Group.objects.get(name='Student')
            user.groups.add(group)

        return user

accounts/views.py
from django.shortcuts import render
from course.models import Enrollment
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import SignupForm


# Create your views here.
class SignupView(CreateView):
    form_class = SignupForm
    template_name = 'register.html'
    success_url = reverse_lazy('accounts:profile')


def profile(request):
    enrollments = Enrollment.objects.filter(student=request.user)
    return render(request, template_name='profile.html', context={'enrollments': enrollments})

course/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from .models import Course, Enrollment
from .models import Category


class HomeView(ListView):
    model = Course
    template_name = 'base/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CourseListView(ListView):
    model = Course
    template_name = 'course_list.html'


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course_detail.html'


def enroll(request, pk):
    course = Course.objects.get(pk=pk)
    e, created = Enrollment.objects.get_or_create(student=request.user, course=course)
    return render(request, template_name='access.html', context={'course': e})


class AccessCourse(DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'access.html'

accounts/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
            <h2>Login</h2>
        </div>
    </div>
    <!-- End Breadcrumbs -->
    <div class='container' data-aos='fade-up' style="margin-top: 5px;">
        {% if form.errors %}
            <p style="color: #fd2d2d"> Username or Password is invalid!</p>
        {% endif %}
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="id_username">Email: </label>
                    <input type="email" name="username" maxlength="128" class="form-control" required=""
                           id="id_username">
                </p>

                <p>
                    <label for="id_password">Password: </label>
                    <input type="password" name="password" maxlength="128" class="form-control" required=""
                           id="id_password">
                </p>
                <button type="submit" class="btn btn-warning">Login</button>
            </form>
        </div>

        <p> New user? <a href="{% url 'accounts:register' %}">Signup</a></p>

    </div>
{% endblock content %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
            <h2>Profile</h2>
        </div>
    </div>
    <!-- End Breadcrumbs -->
    <!-- ======= Profile Section ======= -->
    <section class="d-flex justify-content-center align-items-center">
        <div class="container position-relative" data-aos="fade" data-aos-delay="100">

            <ul class="list-group">
                <li class="list-group-item">{{ user.get_full_name }}</li>
                <li class="list-group-item">{{ user.email }}</li>
            </ul>
        </div>
    </section>
    <!-- End Profile -->
    <!-- ======= Profile Section ======= -->
    <section class="d-flex justify-content-center align-items-center">
        <div class="container position-relative" data-aos="fade" data-aos-delay="100">
            <h3>Enrollments</h3>
            {% if enrollments %}
                {% for enrollment in enrollments %}
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ enrollment.course.thumbnail }}" alt="{{ enrollment.course }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ enrollment.course }}</h5>
                            <p class="card-text">{{ enrollment.course.description }}</p>
                            <a href="{% url 'course:access'  enrollment.course.pk %}" class="btn btn-primary">Learn</a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No course enrolled</p>
            {% endif %}
        </div>
    </section>
    <!-- End Profile -->
{% endblock content %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
            <h2>Register</h2>
        </div>
    </div>
    <!-- End Breadcrumbs -->
    <div class='container' data-aos='fade-up' style="margin-top: 5px;">
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-warning">Register</button>
            </form>
        </div>

        <p> Already a user? <a href="{% url 'accounts:login' %}">Login</a></p>

    </div>
{% endblock content %}

course/templates/base/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">
        <h1>Learning Today,<br>Leading Tomorrow</h1>
        <h2>Join Educative Family and Enhance Your Skills </h2>
        <a href="#" class="btn-get-started">Get Started</a>
    </div>
</section><!-- End Hero -->

<!-- ======= About Section ======= -->
<section id="about" class="about">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>About</h2>
            <p>About Us</p>
        </div>

        <div class="row">
            <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
                <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
                <h3>A group of Developers willing to share their experience</h3>
                <!--                    <p class="font-italic">-->
                <!--                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut-->
                <!--                        labore et dolore-->
                <!--                        magna aliqua.-->
                <!--                    </p>-->
                <ul>
                    <li><i class="icofont-check-circled"></i> Learn from experienced developers
                    </li>
                    <li><i class="icofont-check-circled"></i> Industrial professionals as guest lecturers
                    </li>
                    <li><i class="icofont-check-circled"></i> 3 times a week live doubt clearance
                    </li>
                </ul>
                <a href="#" class="learn-more-btn">Learn More</a>
            </div>
        </div>

    </div>
</section><!-- End About Section -->

<!-- ======= Features Section ======= -->
<section id="features" class="features">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Categories</h2>
            <p>Different category of courses we offer</p>
        </div>

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
            {% for category in categories %}
            <div class="col-lg-3 col-md-4">
                <div class="icon-box">
<!--                    <i class="ri-store-line" style="color: #ffbb2c;"></i>-->
                    <h3><a href="">{{category.name}}</a></h3>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section><!-- End Features Section -->

<!-- ======= Popular Courses Section ======= -->
<section id="popular-courses" class="courses">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Courses</h2>
            <p>Popular Courses</p>
        </div>

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
            {% for course in object_list %}
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                <div class="course-item">
                    <img src="{{ course.thumbnail }}" class="img-fluid" alt="{{ course.name }}">
                    <div class="course-content">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4>{{course.category}}</h4>
                            <p class="price">&#x20B9;{{course.price}}</p>
                        </div>

                        <h3><a href="{% url 'course:courseDetail' course.pk %}">{{course.name}}</a></h3>
                        <p>{{course.description | truncatewords:30}}</p>
                        <div class="trainer d-flex justify-content-between align-items-center">
                            <div class="trainer-profile d-flex align-items-center">
                                <span>{{course.author.get_full_name}}</span>
                            </div>
                            <div class="btn-wrap">
                                <a href="{% url 'course:courseDetail' course.pk %}" class="btn-buy">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End Course Item-->
            {% endfor %}
        </div>

    </div>
</section><!-- End Popular Courses Section -->

<!-- ======= Trainers Section ======= -->
<section id="trainers" class="trainers">
    <!--        <div class="container" data-aos="fade-up">-->

    <!--            <div class="section-title">-->
    <!--                <h2>Trainers</h2>-->
    <!--                <p>Our Professional Trainers</p>-->
    <!--            </div>-->

    <!--            <div class="row" data-aos="zoom-in" data-aos-delay="100">-->
    <!--                <div class="col-lg-4 col-md-6 d-flex align-items-stretch">-->
    <!--                    <div class="member">-->
    <!--                        <img src="assets/img/trainers/trainer-1.jpg" class="img-fluid" alt="">-->
    <!--                        <div class="member-content">-->
    <!--                            <h4>Walter White</h4>-->
    <!--                            <span>Web Development</span>-->
    <!--                            <p>-->
    <!--                                Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis-->
    <!--                                quaerat qui aut aut aut-->
    <!--                            </p>-->
    <!--                            <div class="social">-->
    <!--                                <a href=""><i class="icofont-twitter"></i></a>-->
    <!--                                <a href=""><i class="icofont-facebook"></i></a>-->
    <!--                                <a href=""><i class="icofont-instagram"></i></a>-->
    <!--                                <a href=""><i class="icofont-linkedin"></i></a>-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                </div>-->

    <!--                <div class="col-lg-4 col-md-6 d-flex align-items-stretch">-->
    <!--                    <div class="member">-->
    <!--                        <img src="assets/img/trainers/trainer-2.jpg" class="img-fluid" alt="">-->
    <!--                        <div class="member-content">-->
    <!--                            <h4>Sarah Jhinson</h4>-->
    <!--                            <span>Marketing</span>-->
    <!--                            <p>-->
    <!--                                Repellat fugiat adipisci nemo illum nesciunt voluptas repellendus. In architecto rerum-->
    <!--                                rerum temporibus-->
    <!--                            </p>-->
    <!--                            <div class="social">-->
    <!--                                <a href=""><i class="icofont-twitter"></i></a>-->
    <!--                                <a href=""><i class="icofont-facebook"></i></a>-->
    <!--                                <a href=""><i class="icofont-instagram"></i></a>-->
    <!--                                <a href=""><i class="icofont-linkedin"></i></a>-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                </div>-->

    <!--                <div class="col-lg-4 col-md-6 d-flex align-items-stretch">-->
    <!--                    <div class="member">-->
    <!--                        <img src="assets/img/trainers/trainer-3.jpg" class="img-fluid" alt="">-->
    <!--                        <div class="member-content">-->
    <!--                            <h4>William Anderson</h4>-->
    <!--                            <span>Content</span>-->
    <!--                            <p>-->
    <!--                                Voluptas necessitatibus occaecati quia. Earum totam consequuntur qui porro et laborum-->
    <!--                                toro des clara-->
    <!--                            </p>-->
    <!--                            <div class="social">-->
    <!--                                <a href=""><i class="icofont-twitter"></i></a>-->
    <!--                                <a href=""><i class="icofont-facebook"></i></a>-->
    <!--                                <a href=""><i class="icofont-instagram"></i></a>-->
    <!--                                <a href=""><i class="icofont-linkedin"></i></a>-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                </div>-->

    <!--            </div>-->

    <!--        </div>-->
</section><!-- End Trainers Section -->
{% endblock %}

course/templates/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs" data-aos="fade-in">
    <div class="container">
        <h2>Course Details</h2>
    </div>
</div><!-- End Breadcrumbs -->
<!-- ======= Cource Details Section ======= -->
<section id="course-details" class="course-details">
    <div class="container" data-aos="fade-up">
        {% if course %}
        <div class="row">
            <div class="col-lg-8">
                <img src="{{course.thumbnail}}" class="img-fluid" alt="{{course.name}}">
                <h3>{{course.name}}</h3>
                <p>
                    {{course.description}}
                </p>
            </div>
            <div class="col-lg-4">

                <div class="course-info d-flex justify-content-between align-items-center">
                    <h5>Author</h5>
                    <p><a href="#">{{course.author.get_full_name}}</a></p>
                </div>

                <div class="course-info d-flex justify-content-between align-items-center">
                    <h5>Course Fee</h5>
                    <p>&#x20B9;{{course.price}}</p>
                </div>
                <button class="btn btn-buy"><a href="{% url 'course:enroll' course.pk %}">Enroll</a> </button>
            </div>
        </div>
        {% else %}
        <h3>Course not found</h3>
        {% endif %}
    </div>
</section>
    <!-- End Course Details Section -->

{% endblock %}

course/templates/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs">
    <div class="container">
        <h2>Courses</h2>
        <p>List of Courses we offer</p>
    </div>
</div><!-- End Breadcrumbs -->

<!-- ======= Courses Section ======= -->
<section id="courses" class="courses">
    <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
            {% for course in object_list %}
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                <div class="course-item">
                    <img src="{{course.thumbnail}}" class="img-fluid" alt="{{course.name}}">
                    <div class="course-content">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4>{{ course.category }}</h4>
                            <p class="price">&#x20B9;{{course.price}}</p>
                        </div>

                        <h3><a href="{% url 'course:courseDetail' course.pk %}">{{course.name}}</a></h3>
                        <p>{{course.description|truncatewords:30}}</p>
                        <div class="trainer d-flex justify-content-between align-items-center">
                            <div class="trainer-profile d-flex align-items-center">
                                <img src="#" class="img-fluid" alt="">
                                <span>{{course.author.get_full_name}}</span>
                            </div>
                            <div class="btn-wrap">
                                <a href="{% url 'course:courseDetail' course.pk %}" class="btn-buy">Details</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div> <!-- End Course Item-->
            {% endfor %}
        </div>

    </div>
</section><!-- End Courses Section -->

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Educative</title>
    <!--  <meta content="" name="description">-->
    <!--  <meta content="" name="keywords">-->

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Mentor - v2.1.0
    * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="{% url 'course:home' %}">Educative</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="base.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav class="nav-menu d-none d-lg-block">
                    <ul>
            <!--          <li class="active"><a href="index.html">Home</a></li>-->
            <!--          <li><a href="about.html">About</a></li>-->
                        <li><a href="{% url 'course:courseList' %}">Courses</a></li>
                        <!-- <li><a href="{% url 'course:courseList' %}">Courses</a></li> -->
            <!--          <li><a href="pricing.html">Pricing</a></li>-->
            <!--          <li class="drop-down"><a href="">Drop Down</a>-->
            <!--            <ul>-->
            <!--              <li><a href="#">Drop Down 1</a></li>-->
            <!--              <li class="drop-down"><a href="#">Deep Drop Down</a>-->
            <!--                <ul>-->
            <!--                  <li><a href="#">Deep Drop Down 1</a></li>-->
            <!--                  <li><a href="#">Deep Drop Down 2</a></li>-->
            <!--                  <li><a href="#">Deep Drop Down 3</a></li>-->
            <!--                  <li><a href="#">Deep Drop Down 4</a></li>-->
            <!--                  <li><a href="#">Deep Drop Down 5</a></li>-->
            <!--                </ul>-->
            <!--              </li>-->
            <!--              <li><a href="#">Drop Down 2</a></li>-->
            <!--              <li><a href="#">Drop Down 3</a></li>-->
            <!--              <li><a href="#">Drop Down 4</a></li>-->
            <!--            </ul>-->
            <!--          </li>-->
            <!--          <li><a href="contact.html">Contact</a></li>-->

                    </ul>
        </nav><!-- .nav-menu -->

        <a href="{% url 'account:register' %}" class="get-started-btn">Get Started</a>

    </div>
</header><!-- End Header -->


<!-- ======= Main Section ======= -->
<main id="main" class="container">
    {% block content %}
    {% endblock %}
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="container d-md-flex py-4">

        <div class="mr-md-auto text-center text-md-left">
            <div class="copyright">
                &copy; Copyright <strong><span>Educative</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>